# Generated by Django 6.0.7 on 2026-08-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='mal_id',
            new_name='anilist_id',
        ),
    ]
